services:
  trivia:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: trivia-app
    ports:
      - 8000:8000
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - trivia-net
      - monitoring
    volumes:
      - ./staticfiles:/app/staticfiles
    command: >
      sh -c "
      sleep 10 &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python seed.py &&
      gunicorn --bind 0.0.0.0:8000 trivia_project.wsgi
      "

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - trivia-net

networks:
  trivia-net:
    driver: bridge
  
  monitoring:
    driver: bridge
