# Generated by Django 5.0.9 on 2024-11-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerchoice',
            old_name='answer',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
